import { Image } from "./image.model";

export const IMAGES_DATA: Image[] = [
  { id: 1, category: 'distopia', identified: true },
  { id: 2, category: 'distopia', identified: true },
  { id: 3, category: 'resilencia', identified: true },
  { id: 4, category: 'natura', identified: true },
  { id: 5, category: 'resilencia', identified: true },
  { id: 6, category: 'natura', identified: true },
  { id: 7, category: 'natura', identified: true },
  { id: 8, category: 'natura', identified: true },
  { id: 9, category: 'distopia', identified: true },
  { id: 10, category: 'distopia', identified: true },
  { id: 11, category: 'distopia', identified: true },
  { id: 12, category: 'natura', identified: true },
  { id: 13, category: 'distopia', identified: true },
  { id: 14, category: 'resilencia', identified: true },
  { id: 15, category: 'resilencia', identified: true },
  { id: 16, category: 'residencia', identified: true },
  { id: 17, category: 'distopia', identified: true },
  { id: 18, category: 'distopia', identified: true },
  { id: 19, category: 'resilencia', identified: true },
  { id: 20, category: 'resilencia', identified: true },
  { id: 21, category: 'distopia', identified: true },
  { id: 22, category: 'natura', identified: true },
  { id: 23, category: 'resilencia', identified: true },
  { id: 24, category: 'distopia', identified: true },
  { id: 25, category: 'resilencia', identified: true },
  { id: 26, category: 'resilencia', identified: true },
  { id: 27, category: 'distopia', identified: true },
  { id: 28, category: 'natura', identified: true },
  { id: 29, category: 'natura', identified: true },
  { id: 30, category: 'natura', identified: true },
  { id: 31, category: 'resilencia', identified: true },
  { id: 32, category: 'distopia', identified: true },
  { id: 33, category: 'natura', identified: true },
  { id: 34, category: 'natura', identified: true },
  { id: 35, category: 'natura', identified: true },
  { id: 36, category: 'resilencia', identified: true },
  { id: 37, category: 'resilencia', identified: true },
  { id: 38, category: 'natura', identified: true },
  { id: 39, category: 'distopia', identified: true },
  { id: 40, category: 'resilencia', identified: true },
];